export const MediaStatsMap: any = {
  'video.send.availableBitrate': {
    Name: 'Sent Bandwidth Estimate',
    Category: 'General',
    Units: 'bps',
    Purpose: 'Bandwidth estimation',
    Details:
      'It is calculated by the underlying congestion control by combining the available bitrate for all the outgoing RTP streams.',
    Comments:
      '1.5 MBps or higher is recommended for high-quality video streaming.',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'audio.send.bitrate': {
    Name: 'Send Bitrate',
    Category: 'Audio',
    Units: 'bps',
    Purpose: 'Sent bitrate',
    Details: 'Sent bitrate of audio. Results are in bits per second (bps).',
    Comments: 'General values are in the 24 kbps range (36-128kbps typical)',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'audio.send.packetsPerSecond': {
    Name: 'Sent Packets',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Sent packets',
    Details:
      'The number of audio packets sent in the last second. Results are in packets per second.',
    Comments: '',
    Clickable: true,
  },
  'audio.send.packetsLostPerSecond': {
    Name: 'Lost Send Packets',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Sent packet loss',
    Details:
      'The number of audio packets sent that were lost (not received) in the last second. Results are in packets per second.',
    Comments: 'Lower is better.',
    Clickable: true,
  },
  'audio.send.codecName': {
    Name: 'Send codec',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Sent codec',
    Details: 'Audio codec used for encoding audio.',
    Comments: 'OPUS, G722, etc',
    Clickable: false,
  },
  'audio.send.rttInMs': {
    Name: 'Round-Trip Time',
    Category: 'Audio',
    Units: 'ms',
    Purpose: 'Round-Trip Time',
    Details:
      'Estimated round trip time based on the RTCP timestamps in the RTCP Receiver Report (RR) and measured in milliseconds',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'audio.send.pairRttInMs': {
    Name: 'Pair Round-Trip Time',
    Category: 'Audio',
    Units: 'ms',
    Purpose: 'Pair Round-Trip Time',
    Details:
      'The latest round trip time computed from both STUN connectivity checks. Results are in milliseconds.',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'audio.send.audioInputLevel': {
    Name: 'Microphone Input Level',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Microphone input level.',
    Details: 'Microphone input level. The value ranges from 0-65536.',
    Comments: '0 means silence.',
    Clickable: true,
  },
  'audio.receive.codecName': {
    Name: 'Receive codec',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Received codec',
    Details: 'Audio codec received',
    Comments: 'OPUS, G722, etc',
    Clickable: false,
  },
  'audio.receive.bitrate': {
    Name: 'Receive Bitrate',
    Category: 'Audio',
    Units: 'bps',
    Purpose: 'Received bitrate',
    Details: 'Received bitrate of audio. Results are in bits per second (bps).',
    Comments: '',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'audio.receive.jitterInMs': {
    Name: 'Receive Jitter',
    Category: 'Audio',
    Units: 'ms',
    Purpose: 'Received Jitter',
    Details:
      'Jitter is the variation in the delay of received packets. Results are in milliseconds',
    Comments:
      'Lower is better. Typically, an audio jitter of 30 ms or less is recommended.',
    Clickable: true,
  },
  'audio.receive.packetsLostPerSecond': {
    Name: 'Lost Receive Packets',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Received packet loss',
    Details:
      'The number of audio packets that were to be received but were lost in the last second. Results are in packets per second.',
    Comments: 'Lower is better.',
    Clickable: true,
  },
  'audio.receive.packetsPerSecond': {
    Name: 'Received packets',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Received packets',
    Details:
      'The number of audio packets received in the last second. Results are in packets per second.',
    Comments: 'Information only.',
    Clickable: true,
  },
  'audio.receive.pairRttInMs': {
    Name: 'Pair Round-Trip Time',
    Category: 'Audio',
    Units: 'ms',
    Purpose: 'Pair Round-Trip Time',
    Details:
      'The latest round trip time computed from both STUN connectivity checks. Results are in milliseconds.',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'audio.receive.audioOutputLevel': {
    Name: 'Speaker Output Level',
    Category: 'Audio',
    Units: 'None',
    Purpose: 'Audio stream output level.',
    Details:
      'Audio volume level from the stream received. The value ranges from 0-65536.',
    Comments: '0 means silence.',
    Clickable: true,
  },
  'video.send.frameRateSent': {
    Name: 'Sent Frame Rate',
    Category: 'Video',
    Units: 'fps',
    Purpose: 'Sent frame rate',
    Details:
      'Number of video frames sent in the last second. Results are frames per second',
    Comments: '',
    Clickable: true,
  },
  'video.send.frameWidthSent': {
    Name: 'Sent Width',
    Category: 'Video',
    Units: 'px',
    Purpose: 'Sent width',
    Details: 'Frame width of the encoded frame.',
    Comments: '',
    Clickable: true,
  },
  'video.send.frameHeightSent': {
    Name: 'Sent Height',
    Category: 'Video',
    Units: 'px',
    Purpose: 'Sent height',
    Details: 'Frame height of the encoded frame.',
    Comments: '',
    Clickable: true,
  },
  'video.send.bitrate': {
    Name: 'Send Bitrate',
    Category: 'Video',
    Units: 'bps',
    Purpose: 'Sent bitrate',
    Details: 'Sent bitrate of video. Results are in bits per second (bps).',
    Comments: '',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'video.send.packetsPerSecond': {
    Name: 'Sent Packets',
    Category: 'Video',
    Units: 'None',
    Purpose: 'Sent packets',
    Details:
      'The number of video packets sent in the last second. Results are in packets per second.',
    Comments: 'Information only',
    Clickable: true,
  },
  'video.send.rttInMs': {
    Name: 'Round-Trip Time',
    Category: 'Video',
    Units: 'ms',
    Purpose: 'Round-Trip Time',
    Details:
      'Estimated round trip time based on the RTCP timestamps in the RTCP Receiver Report (RR) and measured in milliseconds',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'video.send.pairRttInMs': {
    Name: 'Pair Round-Trip Time',
    Category: 'Video',
    Units: 'ms',
    Purpose: 'Pair Round-Trip Time',
    Details:
      'The latest round trip time computed from both STUN connectivity checks. Results are in milliseconds.',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'video.send.packetsLostPerSecond': {
    Name: 'Send Packet Loss',
    Category: 'Video',
    Units: 'None',
    Purpose: 'Sent packet loss',
    Details:
      'The number of video packets sent that were lost (not received) in the last second. Results are in packets per second.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'video.send.frameRateInput': {
    Name: 'Sent Framerate Input',
    Category: 'Video',
    Units: 'fps',
    Purpose: 'Sent framerate input',
    Details: 'Framerate measurements from the video source',
    Comments: 'Information only',
    Clickable: true,
  },
  'video.send.frameWidthInput': {
    Name: 'Sent Frame Width Input',
    Category: 'Video',
    Units: 'px',
    Purpose: 'Sent frame width input',
    Details: 'Frame width from the video source',
    Comments: '',
    Clickable: true,
  },
  'video.send.frameHeightInput': {
    Name: 'Sent Frame Height Input',
    Category: 'Video',
    Units: 'px',
    Purpose: 'Sent frame height input',
    Details: 'Frame height from the video source',
    Comments: '',
    Clickable: true,
  },
  'video.send.codecName': {
    Name: 'Send Codec',
    Category: 'Video',
    Units: 'None',
    Purpose: 'Sent codec',
    Details: 'Video codec used for encoding video.',
    Comments: 'H264, VP8',
    Clickable: false,
  },
  'video.receive.codecName': {
    Name: 'Receive Codec',
    Category: 'Video',
    Units: 'None',
    Purpose: 'Received codec',
    Details: 'Received video codec',
    Comments: 'H264, VP8',
    Clickable: false,
  },
  'video.receive.bitrate': {
    Name: 'Received Bitrate',
    Category: 'Video',
    Units: 'bps',
    Purpose: 'Received bitrate',
    Details: 'Received bitrate of video. Results are in bits per second (bps).',
    Comments: '',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'video.receive.packetsPerSecond': {
    Name: 'Received Packets',
    Category: 'Video',
    Units: 'None',
    Purpose: 'Received packets',
    Details:
      'The number of video packets received in the last second. Results are in packets per second.',
    Comments: 'Information Only',
    Clickable: true,
  },
  'video.receive.packetsLostPerSecond': {
    Name: 'Receive Packet Loss',
    Category: 'Video',
    Units: 'None',
    Purpose: 'Received packet loss',
    Details:
      'The number of video packets that were to be received but were lost in the last second. Results are in packets per second.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'video.receive.jitterInMs': {
    Name: 'Receive Jitter',
    Category: 'Video',
    Units: 'ms',
    Purpose: 'Received Jitter',
    Details:
      'Jitter is the variation in the delay of received packets. Results are in milliseconds',
    Comments: 'Lower is better.',
    Clickable: true,
  },
  'video.receive.pairRttInMs': {
    Name: 'Pair Round-Trip Time',
    Category: 'Video',
    Units: 'ms',
    Purpose: 'Pair Round-Trip Time',
    Details:
      'The latest round trip time computed from both STUN connectivity checks. Results are in milliseconds.',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'video.receive.frameRateReceived': {
    Name: 'Received Frame Rate',
    Category: 'Video',
    Units: 'fps',
    Purpose: 'Received frame rate',
    Details:
      'Frame rate received on the RTP stream. Results are in frames per second.',
    Comments: '',
    Clickable: true,
  },
  'video.receive.frameWidthReceived': {
    Name: 'Received Width',
    Category: 'Video',
    Units: 'px',
    Purpose: 'Received width',
    Details: 'Frame width of the decoded frame.',
    Comments: '',
    Clickable: true,
  },
  'video.receive.frameHeightReceived': {
    Name: 'Received Height',
    Category: 'Video',
    Units: 'px',
    Purpose: 'Received height',
    Details: 'Frame height of the decoded frame.',
    Comments: '',
    Clickable: true,
  },
  'video.receive.frameRateOutput': {
    Name: 'Received Frame Rate Output',
    Category: 'Video',
    Units: 'fps',
    Purpose: 'Received framerate output',
    Details: 'Received framerate output. Results are in frames per second.',
    Comments: '',
    Clickable: true,
  },
  'video.receive.frameRateDecoded': {
    Name: 'Received Decoded Frame Rate',
    Category: 'Video',
    Units: 'fps',
    Purpose: 'Received decoded frame rate',
    Details: 'Framerate from decoder output. Results are in frames per second.',
    Comments: 'Information only',
    Clickable: true,
  },
  'video.receive.longestFreezeDurationInMs': {
    Name: 'Received Longest Freeze Duration',
    Category: 'Video',
    Units: 'ms',
    Purpose: 'Received longest freeze duration',
    Details:
      'The longest freeze duration during the call. Results are in milliseconds.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'video.receive.totalFreezeDurationInMs': {
    Name: 'Received Total Freeze Duration',
    Category: 'Video',
    Units: 'ms',
    Purpose: 'Received total freeze duration',
    Details:
      'Accumulated freeze duration during the call. Results are in milliseconds.',
    Comments: 'Lower is better',
    Clickable: true,
  },

  'screenShare.receive.frameRateReceived': {
    Name: 'Received Frame Rate',
    Category: 'Screen Sharing',
    Units: 'fps',
    Purpose: 'Received Frame Rate',
    Details:
      'Frame rate received on the RTP stream. Results are in frames per second.',
    Comments: '',
    Clickable: true,
  },
  'screenShare.receive.frameRateDecoded': {
    Name: 'Received Decoded Frame Rate',
    Category: 'Screen Sharing',
    Units: 'fps',
    Purpose: 'Received decoded frame rate',
    Details: 'Framerate from decoder output. Results are in frames per second.',
    Comments: 'Information only',
    Clickable: true,
  },
  'screenShare.receive.frameWidthReceived': {
    Name: 'Received Width',
    Category: 'Screen Sharing',
    Units: 'px',
    Purpose: 'Received width',
    Details: 'Frame width of the decoded frame.',
    Comments: '',
    Clickable: true,
  },
  'screenShare.receive.frameHeightReceived': {
    Name: 'Received Height',
    Category: 'Screen Sharing',
    Units: 'px',
    Purpose: 'Received height',
    Details: 'Frame height of the decoded frame.',
    Comments: '',
    Clickable: true,
  },
  'screenShare.receive.longestFreezeDurationInMs': {
    Name: 'Received Longest Freeze Duration',
    Category: 'Screen Sharing',
    Units: 'ms',
    Purpose: 'Received longest freeze duration',
    Details:
      'The longest freeze duration during the call. Results are in milliseconds.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'screenShare.receive.totalFreezeDurationInMs': {
    Name: 'Received Total Freeze Duration',
    Category: 'Screen Sharing',
    Units: 'ms',
    Purpose: 'Received total freeze duration',
    Details:
      'Accumulated freeze duration during the call. Results are in milliseconds.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'screenShare.receive.jitterInMs': {
    Name: 'Received Jitter',
    Category: 'Screen Sharing',
    Units: 'ms',
    Purpose: 'Received Jitter',
    Details:
      'Jitter is the variation in the delay of received packets. Results are in milliseconds',
    Comments: 'Lower is better.',
    Clickable: true,
  },
  'screenShare.receive.packetsLostPerSecond': {
    Name: 'Received Packet Loss',
    Category: 'Screen Sharing',
    Units: 'None',
    Purpose: 'Received packet loss',
    Details:
      'The number of screen share video packets that were to be received but were lost in the last second. Results are in packets per second.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'screenShare.receive.codecName': {
    Name: 'Receive Codec',
    Category: 'Screen Sharing',
    Units: 'None',
    Purpose: 'Received codec',
    Details: 'Received screen share video codec',
    Comments: 'H264, VP8',
    Clickable: false,
  },
  'screenShare.receive.bitrate': {
    Name: 'Received Bitrate',
    Category: 'Screen Sharing',
    Units: 'bps',
    Purpose: 'Received bitrate',
    Details:
      'Received bitrate of screen share. Results are in bits per second (bps).',
    Comments: '',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'screenShare.receive.packetsPerSecond': {
    Name: 'Received Packets',
    Category: 'Screen Sharing',
    Units: 'None',
    Purpose: 'Received packets',
    Details:
      'The number of screen share video packets received in the last second. Results are in packets per second.',
    Comments: 'Information Only',
    Clickable: true,
  },
  'screenShare.receive.pairRttInMs': {
    Name: 'Pair Round-Trip Time',
    Category: 'Screen Sharing',
    Units: 'ms',
    Purpose: 'Pair Round-Trip Time',
    Details:
      'The latest round trip time computed from both STUN connectivity checks. Results are in milliseconds.',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'screenShare.receive.frameRateOutput': {
    Name: 'Received Frame Rate Output',
    Category: 'Screen Sharing',
    Units: 'fps',
    Purpose: 'Received framerate output',
    Details: 'Received framerate output. Results are in frames per second.',
    Comments: '',
    Clickable: true,
  },
  'screenShare.send.frameRateSent': {
    Name: 'Sent Frame Rate',
    Category: 'Screen Sharing',
    Units: 'fps',
    Purpose: 'Sent frame rate',
    Details:
      'Number of screen share video frames sent in the last second. Results are frames per second',
    Comments: '',
    Clickable: true,
  },
  'screenShare.send.frameWidthSent': {
    Name: 'Sent Width',
    Category: 'Screen Sharing',
    Units: 'px',
    Purpose: 'Sent width',
    Details: 'Frame width of the encoded frame.',
    Comments: '',
    Clickable: true,
  },
  'screenShare.send.frameHeightSent': {
    Name: 'Sent Height',
    Category: 'Screen Sharing',
    Units: 'px',
    Purpose: 'Sent height',
    Details: 'Frame height of the encoded frame.',
    Comments: '',
    Clickable: true,
  },
  'screenShare.send.bitrate': {
    Name: 'Send Bitrate',
    Category: 'Screen Sharing',
    Units: 'bps',
    Purpose: 'Sent bitrate',
    Details:
      'Sent bitrate of screen share. Results are in bits per second (bps).',
    Comments: '',
    Clickable: true,
    GranularityDivider: 1000,
    GranularityUnits: 'kbps',
  },
  'screenShare.send.packetsPerSecond': {
    Name: 'Sent Packets',
    Category: 'Screen Sharing',
    Units: 'None',
    Purpose: 'Sent packets',
    Details:
      'The number of screen share video packets sent in the last second. Results are in packets per second.',
    Comments: 'Information only',
    Clickable: true,
  },
  'screenShare.send.rttInMs': {
    Name: 'Round-Trip Time',
    Category: 'Screen Sharing',
    Units: 'ms',
    Purpose: 'Round-Trip Time',
    Details:
      'Estimated round trip time based on the RTCP timestamps in the RTCP Receiver Report (RR) and measured in milliseconds',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'screenShare.send.pairRttInMs': {
    Name: 'Pair Round-Trip Time',
    Category: 'Screen Sharing',
    Units: 'ms',
    Purpose: 'Pair Round-Trip Time',
    Details:
      'The latest round trip time computed from both STUN connectivity checks. Results are in milliseconds.',
    Comments: 'A round trip time of 200 ms or less is recommended.',
    Clickable: true,
  },
  'screenShare.send.packetsLostPerSecond': {
    Name: 'Send Packet Loss',
    Category: 'Screen Sharing',
    Units: 'None',
    Purpose: 'Sent packet loss',
    Details:
      'The number of screen share video packets sent that were lost (not received) in the last second. Results are in packets per second.',
    Comments: 'Lower is better',
    Clickable: true,
  },
  'screenShare.send.frameRateInput': {
    Name: 'Sent Framerate Input',
    Category: 'Screen Sharing',
    Units: 'fps',
    Purpose: 'Sent framerate input',
    Details: 'Framerate measurements from the screen share source',
    Comments: 'Information only',
    Clickable: true,
  },
  'screenShare.send.frameWidthInput': {
    Name: 'Sent Frame Width Input',
    Category: 'Screen Sharing',
    Units: 'px',
    Purpose: 'Sent frame width input',
    Details: 'Frame width from the screen share source',
    Comments: '',
    Clickable: true,
  },
  'screenShare.send.frameHeightInput': {
    Name: 'Sent Frame Height Input',
    Category: 'Screen Sharing',
    Units: 'px',
    Purpose: 'Sent frame height input',
    Details: 'Frame height from the screen share source',
    Comments: '',
    Clickable: true,
  },
  'screenShare.send.codecName': {
    Name: 'Send Codec',
    Category: 'Screen Sharing',
    Units: 'None',
    Purpose: 'Sent codec',
    Details: 'Screen share video codec used for encoding video.',
    Comments: 'H264, VP8',
    Clickable: false,
  },
}
